DROP TABLE `audit_logs`;--> statement-breakpoint
DROP TABLE `baptism_registrations`;--> statement-breakpoint
DROP TABLE `bulletins`;--> statement-breakpoint
DROP TABLE `ccd_events`;--> statement-breakpoint
DROP TABLE `ccd_permissions`;--> statement-breakpoint
DROP TABLE `ccd_registrations`;--> statement-breakpoint
DROP TABLE `cyo_games`;--> statement-breakpoint
DROP TABLE `cyo_teams`;--> statement-breakpoint
DROP TABLE `email_subscriptions`;--> statement-breakpoint
DROP TABLE `events`;--> statement-breakpoint
DROP TABLE `funeral_pre_planning`;--> statement-breakpoint
DROP TABLE `gallery_photos`;--> statement-breakpoint
DROP TABLE `holy_days`;--> statement-breakpoint
DROP TABLE `homilies`;--> statement-breakpoint
DROP TABLE `important_dates`;--> statement-breakpoint
DROP TABLE `marriage_inquiries`;--> statement-breakpoint
DROP TABLE `mass_intentions`;--> statement-breakpoint
DROP TABLE `news_posts`;--> statement-breakpoint
DROP TABLE `parish_documents`;--> statement-breakpoint
DROP TABLE `parish_faqs`;--> statement-breakpoint
DROP TABLE `parish_registrations`;--> statement-breakpoint
DROP TABLE `prayer_intentions`;--> statement-breakpoint
DROP TABLE `prayer_support`;--> statement-breakpoint
DROP TABLE `push_subscriptions`;--> statement-breakpoint
DROP TABLE `saint_streaks`;--> statement-breakpoint
DROP TABLE `site_settings`;--> statement-breakpoint
DROP TABLE `sponsor_certificates`;--> statement-breakpoint
DROP TABLE `staff_members`;--> statement-breakpoint
DROP TABLE `teen_life_registrations`;--> statement-breakpoint
DROP TABLE `volunteer_need_responses`;--> statement-breakpoint
DROP TABLE `volunteer_needs`;--> statement-breakpoint
DROP TABLE `volunteer_opportunities`;--> statement-breakpoint
DROP TABLE `volunteer_signups`;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin') NOT NULL DEFAULT 'user';