CREATE TABLE `baptism_registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`childFirstName` varchar(200) NOT NULL,
	`childLastName` varchar(200) NOT NULL,
	`childDob` varchar(20) NOT NULL,
	`childGender` varchar(20) NOT NULL,
	`fatherName` varchar(300),
	`motherName` varchar(300),
	`parentEmail` varchar(320) NOT NULL,
	`parentPhone` varchar(30) NOT NULL,
	`address` text NOT NULL,
	`godparentName1` varchar(300),
	`godparentName2` varchar(300),
	`preferredDate` varchar(50),
	`birthCertUrl` text,
	`notes` text,
	`status` enum('pending','approved','scheduled','completed','cancelled') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `baptism_registrations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `funeral_pre_planning` (
	`id` int AUTO_INCREMENT NOT NULL,
	`plannerName` varchar(300) NOT NULL,
	`plannerEmail` varchar(320) NOT NULL,
	`plannerPhone` varchar(30) NOT NULL,
	`plannerRelation` varchar(100),
	`deceasedName` varchar(300) NOT NULL,
	`isPrePlanning` boolean NOT NULL DEFAULT false,
	`preferredDate` varchar(50),
	`massType` enum('funeral_mass','memorial_mass','vigil_service','graveside') NOT NULL DEFAULT 'funeral_mass',
	`firstReading` text,
	`secondReading` text,
	`gospel` text,
	`hymns` text,
	`eulogist` varchar(300),
	`pallbearers` text,
	`specialRequests` text,
	`status` enum('pending','confirmed','completed') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `funeral_pre_planning_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `marriage_inquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brideFirstName` varchar(200) NOT NULL,
	`brideLastName` varchar(200) NOT NULL,
	`brideEmail` varchar(320) NOT NULL,
	`bridePhone` varchar(30) NOT NULL,
	`brideReligion` varchar(100),
	`brideParish` varchar(300),
	`groomFirstName` varchar(200) NOT NULL,
	`groomLastName` varchar(200) NOT NULL,
	`groomEmail` varchar(320),
	`groomPhone` varchar(30),
	`groomReligion` varchar(100),
	`groomParish` varchar(300),
	`preferredDate` varchar(50),
	`alternateDate` varchar(50),
	`isParishioner` boolean NOT NULL DEFAULT false,
	`previousMarriage` boolean NOT NULL DEFAULT false,
	`previousMarriageDetails` text,
	`guestCount` varchar(20),
	`notes` text,
	`status` enum('pending','in_review','meeting_scheduled','approved','denied') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `marriage_inquiries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sponsor_certificates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorFirstName` varchar(200) NOT NULL,
	`sponsorLastName` varchar(200) NOT NULL,
	`sponsorEmail` varchar(320) NOT NULL,
	`sponsorPhone` varchar(30) NOT NULL,
	`sponsorAddress` text NOT NULL,
	`sponsorParish` varchar(300) NOT NULL,
	`sponsorParishCity` varchar(200) NOT NULL,
	`sacramentType` enum('baptism','confirmation') NOT NULL,
	`candidateName` varchar(300) NOT NULL,
	`ceremonyDate` varchar(50),
	`isBaptized` boolean NOT NULL DEFAULT true,
	`isConfirmed` boolean NOT NULL DEFAULT true,
	`isActiveCatholic` boolean NOT NULL DEFAULT true,
	`notes` text,
	`status` enum('pending','verified','approved','denied') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sponsor_certificates_id` PRIMARY KEY(`id`)
);
