CREATE TABLE `ccd_permissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ccdRegistrationId` int,
	`childFirstName` varchar(200) NOT NULL,
	`childLastName` varchar(200) NOT NULL,
	`childGrade` varchar(20) NOT NULL,
	`parentName` varchar(300) NOT NULL,
	`parentPhone` varchar(30) NOT NULL,
	`parentEmail` varchar(320) NOT NULL,
	`needsBusTransport` boolean NOT NULL DEFAULT false,
	`busPickupLocation` varchar(500),
	`busDropoffLocation` varchar(500),
	`busNotes` text,
	`earlyDismissalAuthorized` boolean NOT NULL DEFAULT false,
	`earlyDismissalReason` text,
	`earlyDismissalDates` text,
	`authorizedPickup1Name` varchar(300) NOT NULL,
	`authorizedPickup1Phone` varchar(30) NOT NULL,
	`authorizedPickup1Relation` varchar(100) NOT NULL,
	`authorizedPickup2Name` varchar(300),
	`authorizedPickup2Phone` varchar(30),
	`authorizedPickup2Relation` varchar(100),
	`authorizedPickup3Name` varchar(300),
	`authorizedPickup3Phone` varchar(30),
	`authorizedPickup3Relation` varchar(100),
	`allergies` text,
	`medications` text,
	`medicalConditions` text,
	`doctorName` varchar(300),
	`doctorPhone` varchar(30),
	`insuranceProvider` varchar(300),
	`insurancePolicyNumber` varchar(100),
	`emergencyContactName` varchar(300) NOT NULL,
	`emergencyContactPhone` varchar(30) NOT NULL,
	`emergencyContactRelation` varchar(100) NOT NULL,
	`photoReleaseConsent` boolean NOT NULL DEFAULT false,
	`medicalReleaseConsent` boolean NOT NULL DEFAULT false,
	`parentSignature` varchar(300) NOT NULL,
	`signatureDate` varchar(20) NOT NULL,
	`status` enum('pending','approved','flagged') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`schoolYear` varchar(20) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ccd_permissions_id` PRIMARY KEY(`id`)
);
